# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/stockprediction
spring.datasource.username=root
spring.datasource.password=Harshuad@1030

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=8080

# App Name
spring.application.name=stock-price-prediction

alphavantage.api.key=H8DHCQEXQVRQY5VN